christianblais/triggerify

- config/initializers/shopify_app.rb
> Add inventory access scope

- app/models/filter.rb
Fixes CI and prevent mutation of argument.
cc @christianblais
> [Filter] Validation to not mutate arguments

- app/jobs/application_job.rb
- app/jobs/callback_webhook_job.rb
Still not great to have auto-retry on error missing, but for now my focus is to raise visibility.
> Callback job track rule specific exceptions

- config/initializers/bugsnag.rb
Add some logs in development when exceptions are rescued and sent to bugsnag.
> [Bugsnag] Add development logging

- lib/parser.rb
- test/lib/parser_test.rb
@christianblais 👀 plz.
I kinda want to re-write this black box to make it more obvious what's up in there, but for now I just want to prevent an exception from preventing a handler execution.
Do you see unforeseen side effects to this change?
> [Parser] Do not allow arbitrary invocation of arrays

- test/controllers/rules_controller_test.rb
- test/fixtures/filters.yml
- test/fixtures/handlers.yml
- test/fixtures/rules.yml
- test/fixtures/shops.yml
> Start some basic tests

- config/initializers/bugsnag.rb
Added https://devcenter.heroku.com/articles/dyno-metadata
This will make Bugsnag report the current SHA as version.
> [Bugsnag] Add version

- lib/filter_validator.rb
- test/lib/filter_validator_test.rb
https://app.bugsnag.com/hooklys/triggerify/errors/5edfd7cd8917270018a30051?filters[event.since][0]=30d&filters[error.status][0]=open
Arrays was already working as there was an `Array.wrap`, hashes were not.
> Fix filter validation error

- app/controllers/rules_controller.rb
- db/migrate/20210903193957_add_interacted_at_to_shop.rb
- db/schema.rb
Add some tracking for user activity to be used later down the process.
> Add shops.interacted_at

- app/models/handler.rb
- app/models/handlers/base.rb
- app/models/handlers/datadog_event.rb
- app/models/handlers/gift_card.rb
- app/models/handlers/send_grid.rb
- app/models/handlers/slack.rb
- app/models/handlers/sms.rb
- app/models/handlers/tagger.rb
- app/models/handlers/twitter.rb
Convert handlers silent returns code path to raise `UserError` which is handled in the handler processing main code path.
> Introduce user errors

- lib/handlers/base.rb
Extraction from https://github.com/christianblais/triggerify/pull/85
> Add NotImplementedError in Handlers::Base

- app/javascript/shopify_app/shopify_app.js
This _should_ work. What could go wrong?
> Listen for all DOM changes, not just turbolinks

- app/javascript/packs/rules.js
- app/views/rules/_filter.html.erb
- app/views/rules/_form.html.erb
- app/views/rules/_handler.html.erb
- lib/polaris_form_builder.rb
Should be easier to create polaris forms from now on. Error state on selects still doesn't work, that's the next step.
> Polaris form builder

- app/jobs/shop_job.rb
- app/models/filter.rb
- test/fixtures/filters.yml
> Polish rough edges

- app/models/handler.rb
- test/jobs/callback_webhook_job_test.rb
- test/models/handler_test.rb
- test/models/rule_test.rb
Extraction from https://github.com/christianblais/triggerify/pull/113
> Add test coverage

- lib/handlers/tagger.rb
- test/lib/handlers/tagger_test.rb
Shopify server based errors to be converted as UserError
> Tagger handle bad identifier

- lib/handlers/emailer.rb
- lib/handlers/send_grid.rb
- test/lib/handlers/emailer_test.rb
- test/lib/handlers/sendgrid_test.rb
Converting the system into a user error quickly.
We could iterate to add more information, but for now I settle on a small step forward.
> Sendgrid invalid emails user errors

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- config/database.yml
- db/schema.rb
Prod environment on PG, so let's move our dev over there too. Bye bye SQlite.
@tjoyal
> From SQlite to PG

- app/jobs/callback_webhook_job.rb
- app/models/handler.rb
- app/models/rule.rb
- app/models/rule_event.rb
- app/models/rule_event_detail.rb
- app/models/rule_event_repository.rb
- db/migrate/20220226134505_add_events_to_rules.rb
- db/schema.rb
- lib/rule_runner.rb
- test/jobs/callback_webhook_job_test.rb
- test/lib/rule_runner_test.rb
- test/models/handler_test.rb
- test/models/rule_event_detail_test.rb
- test/models/rule_event_repository_test.rb
- test/models/rule_event_test.rb
- test/models/rule_test.rb
Alternative on https://github.com/christianblais/triggerify/pull/113 with `RuleEventRepository`
Keep the last 10 events on each rules
> [Rule] Keep last events with repository

- app/views/rules/activity.html.erb
- test/controllers/rules_controller_test.rb
In order to get the latest event on top
> Activity: Events in reverse order

- app/javascript/components/rules/index.js
> Add delete confirmation modal

- lib/handlers/emailer.rb
- lib/handlers/send_grid.rb
- lib/handlers/slack.rb
- lib/handlers/sms.rb
- lib/handlers/tagger.rb
- lib/handlers/twitter.rb
- test/lib/handlers/emailer_test.rb
- test/lib/handlers/sendgrid_test.rb
- test/lib/handlers/slack_test.rb
- test/lib/handlers/sms_test.rb
- test/lib/handlers/tagger_test.rb
Since those errors are meant for consumption, I'm trying to make them a little more legible. Thoughts?
> More legible error messages

- app/javascript/components/rules/activity.js
Merging. Feel free to edit as you see fit.
> Empty activity state

- app/javascript/components/rules/templates.js
- app/models/rule_template.rb
Trying to take customers by the hand a little bit more.
> New template, and tweaks to description

- app/models/rule_template.rb
This is another one that comes often.
> Email on tagged customer

- app/javascript/components/rules/index.js
> Rule index refactor

- app/controllers/rules_controller.rb
- app/views/rules/_form.html.erb
It is not quite perfect as there is still a double server render. 
This has not been introduced by this PR so I think this can go in as a step forward with the desired behaviour.
> Rule create/update to redirect to index page

- app/controllers/callback_controller.rb
- app/javascript/components/rules/activity.js
- app/jobs/callback_webhook_job.rb
- app/models/rule_event.rb
- lib/rule_runner.rb
- test/jobs/callback_webhook_job_test.rb
- test/lib/rule_runner_test.rb
- test/models/rule_event_repository_test.rb
- test/models/rule_event_test.rb
- test/models/rule_test.rb
Dependent on https://github.com/tjoyal/krishna/pull/401
When present, add a link back to Hooklys
> Add link to Hooklys details

- app/javascript/components/layouts/footer.js
- app/views/layouts/embedded_app.html.erb
> Add feedback footer
